using System.ComponentModel;

namespace Сodem.Shared.Enums;

public enum ProgrammingLanguage
{
    [Description("C")]
    C,
    [Description("C++")]
    Cpp,
    [Description("CSS")]
    Css,
    [Description("HTML")]
    Html,
    [Description("Java")]
    Java,
    [Description("JavaScript")]
    JavaScript,
    [Description("JSON")]
    Json,
    [Description("JSX")]
    Jsx,
    [Description("MariaDB SQL")]
    MariaDbSql,
    [Description("Markdown")]
    Markdown,
    [Description("MS SQL")]
    Mssql,
    [Description("MySQL")]
    MySql,
    [Description("PHP")]
    Php,
    [Description("PostgreSQL")]
    PostgreSQL,
    [Description("Python")]
    Python,
    [Description("Rust")]
    Rust,
    [Description("SQL")]
    Sql,
    [Description("SQLite")]
    SqLite,
    [Description("TSX")]
    Tsx,
    [Description("TypeScript")]
    TypeScript,
    [Description("XML")]
    Xml,
    [Description("C#")]
    CSharp,
    [Description("CMake")]
    CMake,
    [Description("Cython")]
    Cython,
    [Description("Dart")]
    Dart,
    [Description("Dockerfile")]
    Dockerfile,
    [Description("Erlang")]
    Erlang,
    [Description("Fortran")]
    Fortran,
    [Description("F#")]
    FSharp,
    [Description("Go")]
    Go,
    [Description("Groovy")]
    Groovy,
    [Description("Haskell")]
    Haskell,
    [Description("HTTP")]
    Http,
    [Description("Jinja2")]
    Jinja2,
    [Description("Kotlin")]
    Kotlin,
    [Description("LESS")]
    LESS,
    [Description("Lua")]
    Lua,
    [Description("Nginx")]
    Nginx,
    [Description("Objective-C")]
    ObjectiveC,
    [Description("Objective-C++")]
    ObjectiveCpp,
    [Description("Pascal")]
    Pascal,
    [Description("Perl")]
    Perl,
    [Description("PowerShell")]
    PowerShell,
    [Description("Ruby")]
    Ruby,
    [Description("Sass")]
    Sass,
    [Description("SCSS")]
    Scss,
    [Description("Shell")]
    Shell,
    [Description("Swift")]
    Swift,
    [Description("sTeX")]
    STeX,
    [Description("LaTeX")]
    LaTeX,
    [Description("TOML")]
    Toml,
    [Description("VB.NET")]
    VbNet,
    [Description("YAML")]
    Yaml
}