using System.ComponentModel;

namespace Сodem.Shared.Enums;

public enum ProgrammingLanguage
{
    [Description("C")]
    C,
    [Description("C++")]
    CPP,
    [Description("CSS")]
    CSS,
    [Description("HTML")]
    HTML,
    [Description("Java")]
    Java,
    [Description("JavaScript")]
    JavaScript,
    [Description("JSON")]
    JSON,
    [Description("JSX")]
    JSX,
    [Description("MariaDB SQL")]
    MariaDBSQL,
    [Description("Markdown")]
    Markdown,
    [Description("MS SQL")]
    MSSQL,
    [Description("MySQL")]
    MySQL,
    [Description("PHP")]
    PHP,
    [Description("PostgreSQL")]
    PostgreSQL,
    [Description("Python")]
    Python,
    [Description("Rust")]
    Rust,
    [Description("SQL")]
    SQL,
    [Description("SQLite")]
    SQLite,
    [Description("TSX")]
    TSX,
    [Description("TypeScript")]
    TypeScript,
    [Description("XML")]
    XML,
    [Description("C#")]
    CSharp,
    [Description("CMake")]
    CMake,
    [Description("Cython")]
    Cython,
    [Description("Dart")]
    Dart,
    [Description("Dockerfile")]
    Dockerfile,
    [Description("Erlang")]
    Erlang,
    [Description("Fortran")]
    Fortran,
    [Description("F#")]
    FSharp,
    [Description("Go")]
    Go,
    [Description("Groovy")]
    Groovy,
    [Description("Haskell")]
    Haskell,
    [Description("HTTP")]
    HTTP,
    [Description("Jinja2")]
    Jinja2,
    [Description("Kotlin")]
    Kotlin,
    [Description("LESS")]
    LESS,
    [Description("Lua")]
    Lua,
    [Description("Nginx")]
    Nginx,
    [Description("Objective-C")]
    ObjectiveC,
    [Description("Objective-C++")]
    ObjectiveCPP,
    [Description("Pascal")]
    Pascal,
    [Description("Perl")]
    Perl,
    [Description("PowerShell")]
    PowerShell,
    [Description("Ruby")]
    Ruby,
    [Description("Sass")]
    Sass,
    [Description("SCSS")]
    SCSS,
    [Description("Shell")]
    Shell,
    [Description("Swift")]
    Swift,
    [Description("sTeX")]
    STeX,
    [Description("LaTeX")]
    LaTeX,
    [Description("TOML")]
    TOML,
    [Description("VB.NET")]
    VBNET,
    [Description("YAML")]
    YAML
}